name: Bot Inversor Diario
on:
  schedule:
    - cron: '0 13 * * *' # Se ejecuta autom√°ticamente a las 10:00 AM (Arg/Chile)
  workflow_dispatch: # Esto nos permite probarlo manualmente ahora

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Instalar librerias
        run: pip install requests google-generativeai
      - name: Ejecutar script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: python mi_bot.py
